### PR TITLE
Fix removal of debonding delegations

### LINKED ISSUE #120: Debondings aren't removed after debond_end
Current epoch: 16345

https://index.oasislabs.com/v1/consensus/accounts/oasis1qzv2rktycpcykhudyvg5l6u75v08lpfcw5nt7aj5/debonding_delegations
still returns
```json
{
  "debonding_delegations": [
    {
      "amount": 20528140536507,
      "shares": 20528140536507,
      "address": "oasis1qzv2rktycpcykhudyvg5l6u75v08lpfcw5nt7aj5",
      "debond_end": 14230
    },
    {
      "amount": 143951862299182,
      "shares": 143951862299182,
      "address": "oasis1qzv2rktycpcykhudyvg5l6u75v08lpfcw5nt7aj5",
      "debond_end": 15617
    }
  ]
}
```
sum = 164480002835689

and that includes account summary too
https://index.oasislabs.com/v1/consensus/accounts/oasis1qzv2rktycpcykhudyvg5l6u75v08lpfcw5nt7aj5
```json
{
  "address": "oasis1qzv2rktycpcykhudyvg5l6u75v08lpfcw5nt7aj5",
  "nonce": 18,
  "available": 164496118213225,
  "escrow": 199706193527015700,
  "debonding": 10196635539921422,
  "delegations_balance": 1788162093296800,
  "debonding_delegations_balance": 164480002835689,
  "allowances": []
}
```

(probably related to https://github.com/oasisprotocol/oasis-indexer/issues/84 fixes)

### PR DESCRIPTION
**Pull request by aefhm**
**Why**
Close #120

### CODE REVIEW

File: analyzer/consensus/queries.go [hunk 1]
```diff
@@ -251,16 +251,18 @@ func (qf QueryFactory) ReclaimEscrowBalanceUpdateQuery() string {
...
 				FROM %[1]s.debonding_delegations
 				WHERE
-					delegator = $1 AND delegatee = $2 AND shares = $3 AND debond_end = (
-					SELECT max(id)
+					delegator = $1 AND delegatee = $2 AND shares = $3 AND debond_end IN (
+					SELECT id
 					FROM %[1]s.epochs
-					WHERE end_height IS NOT NULL AND end_height < $4
+					ORDER BY id DESC
+					LIMIT 2
```
Comment (ennsharma) [inline analyzer/consensus/queries.go:265]: If you just need the second-biggest can you do `LIMIT 1 OFFSET 1`? Or do we really need both?

**Review by ennsharma — APPROVED** [review]

File: analyzer/consensus/queries.go (hunk 1 above)
Comment (aefhm) [reply analyzer/consensus/queries.go:265]: In the case of a network upgrade, it is the second biggest. Otherwise, it is the biggest. 😬 😅
