### PR TITLE
 storage client: get entire address preimage 

### LINKED ISSUE #365: sender_0_eth doesn't check AddressPreimage context before converting oasis1 address
##### ISSUE TYPE
- Bug Report

##### STEPS TO REPRODUCE

Transaction endpoint returns `sender_0_eth` for `consensus.Deposit` transactions

https://index-staging.oasislabs.com/v1/emerald/transactions/2b1a30eb672c4dbec92804b8144f3675c2ebc22d3c3993ca1513274fdf0a1cbe
```json
 "sender_0": "oasis1qzypxmt5xg8039329zvre7hxe7kn0vxfugsknqtw",
 "sender_0_eth": "0xa8E1A15b898df5B6807F034f7160cd6B8018937C",
```

but it looks like that account has a consensus staking context:

https://index-staging.oasislabs.com/v1/emerald/accounts/oasis1qzypxmt5xg8039329zvre7hxe7kn0vxfugsknqtw
```json
  "address": "oasis1qzypxmt5xg8039329zvre7hxe7kn0vxfugsknqtw",
  "address_preimage": {
    "address_data": "HBex6gIKmPD/qJoyqOGhW4mN9baAfwNPcWDNa4AYk3w=",
    "context": "oasis-core/address: staking",
    "context_version": 0
  },
```

### PR DESCRIPTION
**Pull request by pro-wh**
~~fixes #365~~

1. adjust some specs to use our custom string Address type
2. ~~get all related address preimage info when querying transaction~~
3. ~~don't set incorrect xxx_eth address when preimage is not secp256k1eth~~

EthAddrReference is moved out to client package. changed to EthChecksumAddrFromPreimage

### CODE REVIEW

**Comment by mitjat** [comment]
Are there regression changes with `reindex_and_run.sh`? Asking largely because I have an upcoming PR that will be a total merge conflict with this one, so ideally this _would_ result in some changes that I then can make sure my PR preserves post-rebase.

File: storage/client/queries/queries.go [hunk 1]
```diff
@@ -311,7 +311,11 @@ const (
 			txs.result_raw,
 			(
 				SELECT
-					json_object_agg(pre.address, encode(pre.address_data, 'hex'))
+					json_object_agg(pre.address, json_build_object(
```
Comment (mitjat) [inline storage/client/queries/queries.go:314]: Why do we pull all this into Go? Does the consumer of this SELECT care about non-eth preimages? If not, I'd prefer to keep it simple and just add a `WHERE pre.context_identifier = ... AND pre.context_version = ...` here.

**Review by aefhm — APPROVED** [review]

File: storage/client/queries/queries.go (hunk 1 above)
Comment (mitjat) [reply storage/client/queries/queries.go:314]: Or rather, I should say: https://github.com/oasisprotocol/oasis-indexer/pull/368 pulls in just the eth preimages and discards other preimages. Is it OK to leave it that way, assuming I get the rest of the git merge right after this PR?

Comment (pro-wh) [reply storage/client/queries/queries.go:314]: it's nice to keep the preimage data together :shrug:

Comment (pro-wh) [reply storage/client/queries/queries.go:314]: will have to look at #368

Comment (pro-wh) [reply storage/client/queries/queries.go:314]: :facepalm: I just realized the whole column is called eth_addr_lookup to begin with

Comment (mitjat) [reply storage/client/queries/queries.go]: Urgh I didn't think of this PR when I merged #368. Sorry I bulldozed it a little. I still think pulling the context is a bit of premature generalization, but yeah it can be nice in the future. Thanks for including the filtering on the DB side too, for now. And sorry for the rebase!

**Review by mitjat — APPROVED** [review]

File: storage/client/client.go [hunk 2]
```diff
@@ -1084,12 +1108,13 @@ func (c *StorageClient) RuntimeTransactions(ctx context.Context, p apiTypes.GetR
 		if t.Success != nil && *t.Success {
 			t.Error = nil
 		}
-		// Fancy-format eth addresses: Apply checksum capitalization, prepend 0x.
-		if t.Sender0Eth != nil {
-			*t.Sender0Eth = ethCommon.HexToAddress(*t.Sender0Eth).Hex()
+		// Render Ethereum-compatible address preimages. In the database
+		// layer. Why are we like this.
```
[the remark this answers is not in the document]
Comment (pro-wh) [reply storage/client/client.go:1112]: let's leave it like this forever, unless the frontend someday wants to display other preimage info as well

File: storage/client/client.go [hunk 3]
```diff
@@ -17,6 +17,7 @@ import (
 	staking "github.com/oasisprotocol/oasis-core/go/staking/api"
 	oasisConfig "github.com/oasisprotocol/oasis-sdk/client-sdk/go/config"
 
+	"github.com/oasisprotocol/oasis-indexer/analyzer/runtime"
```
Comment (pro-wh) [inline storage/client/client.go:20]: this goes the wrong way. analyzer should depend on storage instead. moving `EVMEthAddrFromPreimage` to be with `EthChecksumAddrFromPreimage` here

File: storage/client/client.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (pro-wh) [reply storage/client/client.go:1122]: nvm adding todo :laughing:

File: storage/client/queries/queries.go (hunk 1 above)
Comment (pro-wh) [reply storage/client/queries/queries.go]: :building_construction:
