### PR TITLE
db client: Simplify, clean up

### LINKED ISSUE #279: Return HTTP 404 for non-existing objects
Requesting a non-existing object, e.g. `/v1/consensus/entities/aaaaaaaaaaaaaaa+5RKkkfOTUR+XheHIohlqMu+a9As=/nodes/1TDdhVK+R8N6KYNAvGFV4LeFQfp06+sjJI7SgTsN35c=`, currently returns `HTTP 500  internal server error` because the DB backend fails to fetch a row from the DB.

Recognize that type of error and propagate it in a way that it produces a 404.

### PR DESCRIPTION
**Pull request by mitjat**
This PR cleans up a bunch of small things around our DB client that have been bothering me for months, but even more so lately when I've been interacting with the DB more.
Changes/improvements:
- Removes copy-pasted error logs when a SQL query fails. We log these errors in our DB wrapper library, and `pgx` proper logs them also, so they were triple-logged previously. (For QueryRow(), `pgx` design is a little different and we cannot easily have a wrapper there, so we don't log the error ourselves. Those errors used to be double-logged, and are now single-logged, by pgx.)
- Obviates manual decoding of BigInts when pulled from the DB; I added a method to `BigInt` that `pgx` can use to do the decoding automatically. It doesn't work for `*BigInt` (= API fields that are nillable) due to a pgx bug/restriction. I spent way too much time trying alternatives, including pgx v5 (which has a different API for custom types), but it looks like we best stick with what we have.
- Propagates "no row found" from QueryRow() into a HTTP 404. This resolves #279 . This commit is also a good starting point for anybody wanting to create more custom errors.
- Simplifies the construction of QueryFactory objects. We had a bunch of copy-pasted code that always fetched the chainId and runtime from the `ctx`; now, this happens in a helper func.

### CODE REVIEW

File: api/middleware.go [hunk 1]
```diff
@@ -235,9 +235,15 @@ func RuntimeFromURLMiddleware(baseURL string) func(next http.Handler) http.Handl
 			// The first part of the path (after the version) determines the runtime.
 			// Recognize only whitelisted runtimes.
 			runtime := ""
-			switch { //nolint:gocritic // allow single-case switch for future expansions
+			switch {
```
Comment (aefhm) [inline api/middleware.go:238]: Should we also error check or throw?

**Review by aefhm — APPROVED** [review]

File: common/types.go [hunk 2]
```diff
@@ -33,6 +36,56 @@ func (b *BigInt) UnmarshalJSON(text []byte) error {
...
+	*b = bigInt
+	return err
+}
+
+func (b BigInt) EncodeBinary(ci *pgtype.ConnInfo, buf []byte) (newBuf []byte, err error) {
+	numeric := pgtype.Numeric{Int: &b.Int, Exp: 0, Status: pgtype.Present}
+	return numeric.EncodeBinary(ci, buf)
+}
+
+// TODO: DEDUPLICATE - DO NOT SUBMIT PR BEFORE FIXING THIS
```
[the remark this answers is not in the document]
Comment (mitjat) [reply common/types.go]: :+1: this is fixed already, you were probably looking at an intermediate commit

File: api/middleware.go (hunk 1 above)
Comment (mitjat) [reply api/middleware.go:238]: You mean in case no runtime matches? No, there are legitimate URL that just don't have an associated runtime, not even a runtime in the loose sense of "proper runtime or consensus". Example: `/v1/spec/v1.yaml`.

File: api/errors.go [hunk 3]
```diff
@@ -19,21 +20,32 @@ var (
...
 )
 
+type ErrStorageError struct{ Err error }
+
+func (e ErrStorageError) Error() string { return fmt.Sprintf("storage error: %s", e.Err.Error()) }
+
 func HttpCodeForError(err error) int {
-	errType := reflect.ValueOf(err).Elem().Type()
+	errVal := reflect.ValueOf(err)
+	// dereference an interface of pointer
```
Comment (Andrew7234) [inline api/errors.go:34]:
```suggestion
	// dereference an interface or pointer
```

File: storage/client/client.go [hunk 4]
```diff
@@ -256,29 +189,19 @@ func (c *StorageClient) Transactions(ctx context.Context, p apiTypes.GetConsensu
...
 		var code uint64
-		var feeNum pgtype.Numeric
 		if err := rows.Scan(
 			&t.Block,
 			&t.Index,
 			&t.Hash,
 			&t.Sender,
 			&t.Nonce,
-			&feeNum,
+			&t.Fee,
```
Comment (Andrew7234) [inline storage/client/client.go:198]: Just checking - this works for the custom db types (`UINT63` + `UINT31`) now?

**Review by Andrew7234 — APPROVED** [review]

File: storage/client/client.go (hunk 4 above)
Comment (mitjat) [reply storage/client/client.go:198]: I believe it always worked for those. The new thing is that it now works for `UINT_NUMERIC` (and `NUMERIC` variants in general), thanks to commit [`e7de6a4`](https://github.com/oasisprotocol/oasis-indexer/pull/297/commits/e7de6a4172b2eedaca4cfd643c708ca23bf6c7c2)
